[project]
name = "cover-letter-writer"
version = "1.5"
description = "A tool to generate a cover letter using a LLM"
readme = "README.md"
requires-python = ">=3.14, <3.15"
dependencies = [
    "fastapi[standard]==0.129.0",
    "pypdf==6.7.1",
    "requests==2.32.5",
]

[dependency-groups]
dev = [
    "pytest==9.0.2",
]
